  'theme' => 'wechangetheme',
  'social_login_auto_redirect' => true,
  'default_language' => 'de',
  'default_locale' => 'de',
  'allow_user_to_change_display_name' => false,
  'wechange_plattform_root' => '<root-domain-of-plattform-without-trailing-slash>',